project:
  type: website
  output-dir: docs

website:
  title: "Tidyverse"
  navbar:
    logo: img/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: apoyo.qmd
        text: Recursos de apoyo
      - text: "More"
        menu:
          - apoyo.qmd
          - 3_Data_import.qmd 

        
    right:
      - icon: github
        href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - part_1_prep.qmd
      - part_2_eda.qmd
  page-navigation: true

format:
  html:
    theme: sketchi
    css: styles.css
    toc: true

editor: visual

