project:
  type: website
  output-dir: docs

website:
  title: "Tidyverse"
  navbar:
    logo: img/logo.png
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: About
      - href: apoyo.qmd
        text: Recursos de apoyo
      - text: "Secciones"
        menu:
          - 1_Introduccion.qmd
          - 2_RBasico.qmd
          - 3_Proyectos.qmd
          - 4_ImportarDatos.qmd
          - 5_DataWrangling.qmd
          - 5.visualization_ggplot.qmd
          - 6.visualization_ggplot_pt2.qmd
          - 7.ggplot_sin_codigo.qmd

        
    right:
      - icon: github
        href: https://github.com
  # sidebar:
  #   style: "docked"
  #   border: true
  #   search: true
  #   background: light
  #   contents:
  #     - 2.Proyectos.qmd
  #     - 3.Data_import.qmd
  #     - 4.data_wrangling.qmd
  #     - 5.visualization_ggplot.qmd
  #     - 6.visualization_ggplot_pt2.qmd
  #     - 7.ggplot_sin_codigo.qmd
  page-navigation: true

format:
  html:
    grid: 
      body-width: 950px
      margin-width: 250px
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-title: Contenido
    number-sections: true
    number-depth: 2
    toc-expand: true
    page-layout: article # provides content area with margins


editor: visual

