project:
  type: website
  output-dir: docs

website:
  title: "Tidyverse"
  navbar:
    logo: img/logo.png
    left:
      - href: index.qmd
        text: Inicio

      - text: "Secciones"
        menu:
          - 1_Introduccion.qmd
          - 2_RBasico.qmd
          - 3_Proyectos.qmd
          - 4_ImportarDatos.qmd
          - 5_DataWrangling.qmd
          - 6_VisualizationGgplot.qmd
          - 7_VisualizationGgplot2.qmd
          - 8_ggplotNoCode.qmd
          - 9_Union.qmd
          - 10_Across.qmd
          - 11_TimeSeries.qmd
      - href: apoyo.qmd
        text: Recursos de apoyo
    right:
      - icon: github
        href: https://github.com/trippv/CursoTidyverse2023



format:
  html:
    grid: 
      body-width: 1200px
      margin-width: 200px
      sidebar-width: 270px # incremento el espacio del toc
    theme: cosmo
    css:  styles.css
    toc: true
    toc-title: Contenido
    number-sections: false
    toc-expand: 1
    toc-location: left
    page-layout: article # provides content area with margins
    page-navigation: true

dependencies:
  - quarto-ext/fontawesome

editor: visual

