project:
  type: website
  output-dir: docs

website:
  title: "Tidyverse"
  navbar:
    logo: img/logo.png
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: About
      - href: apoyo.qmd
        text: Recursos de apoyo
      - text: "Secciones"
        menu:
          - apoyo.qmd
          - 3_Data_import.qmd 

        
    right:
      - icon: github
        href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - 2.Proyectos.qmd
      - 3.Data_import.qmd
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: Contenido
    number-sections: true
    number-depth: 3
    page-layout: article

editor: visual

