---
title: "Recursos de apoyo"
---

A continuación encontrarás diversos materiales disponibles en la red con la que puedes ampliar tus conocimientos en R y ciencia de datos

-   Libros en línea

    -   [R para Ciencia de Datos](https://es.r4ds.hadley.nz/) - Versión en español de conocido libro "*R for Data Science"* de Wickham y Grolemund.

    -   [The Big Book of R](https://www.bigbookofr.com/) - Extensa colección de libros y materiales en línea.

    -   [Data Visualization with R](https://rkabacoff.github.io/datavis/) - Libro para la creación de gráficos en ggplot.

    -   [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) - Guía para generar visualizaciones efectivas.

    -   [Quarto](https://quarto.org/docs/books/) - Guia para generar reportes, páginas web y documentos PDF con Quarto

-   A quien seguir

    -   [PositPBC](https://www.youtube.com/@PositPBC/featured) - Seminarios, tutoriales y comentarios sobre las últimas novedades de la comunidad de Rstudio (Posit).

    -   [R ladies](https://www.youtube.com/@RLadiesGlobal) - R-Ladies es una organización mundial cuya misión es promover la diversidad de género en la comunidad R.

    -   [Community of Bioinformatics Software Developers](https://www.youtube.com/@CDSB/videos) - Canal de bioinformática con númerosos tutoriales de R desde nivel principiante hasta análisis avanzados.

    -   [Albert Rapp](https://www.youtube.com/@rappa753/videos) - Contiene numerosos tutoriales básicos y avanzados para el análisis de datos en R

-   Cheat Sheets

    -   [Dplyr](https://rstudio.github.io/cheatsheets/data-transformation.pdf)
    -   [ggplot2](https://rstudio.github.io/cheatsheets/data-visualization.pdf)
    -   [readr](https://rstudio.github.io/cheatsheets/data-import.pdf)
    -   [stringr](https://rstudio.github.io/cheatsheets/strings.pdf)
    -   [y muchos otros](https://posit.co/resources/cheatsheets/)
