---
title: "Análisis de datos con Tidyverse"
---

Lugar: **Centro de Investigaciones Biológicas del Noroeste, S.C.**

Instructores: [Miguel A. Tripp Valdez](https://migueltrippcv.netlify.app/)

------------------------------------------------------------------------

**Tidyverse** es un conjunto de paquetes dentro del ambiente R que comparten una misma filosofía y gramática lo que facilita la organización, transformación y visualización de datos tabulares.

::: {.callout-tip icon="false"}
## Objetivos del curso

-   Que el alumno adquiera experiencia práctica en la utilización de herramientas de Tidyverse, dentro del ambiente R, para ordenar, transformar y visualizar datos tabulares.
:::

#### Requisitos

-   Tener experiencia minima en el uso de R

-   Tener computadora personal y acceso a internet

## Temario del curso

+-------------+----------------+-----------------------------------------------------+
| Día         | Hora           | Tema                                                |
+=============+================+=====================================================+
| Lunes       | 10:00 - 14:00  | **Introducción**                                    |
|             |                |                                                     |
|             |                | -   Introducción a R y Tidyverse                    |
|             |                |                                                     |
|             |                | -   Creación y organización de proyectos en Rstudio |
|             |                |                                                     |
|             |                | -   Importar y exportar datos                       |
|             |                |                                                     |
|             |                | -   Tibbles                                         |
+-------------+----------------+-----------------------------------------------------+
| Martes      | 10:00 - 14:00  | **Manipulación de datos con Dplyr**                 |
|             |                |                                                     |
|             |                | -   `select()`                                      |
|             |                |                                                     |
|             |                | -   `filter()`                                      |
|             |                |                                                     |
|             |                | -   `mutate()`                                      |
|             |                |                                                     |
|             |                | -   pipes `%>%`                                     |
|             |                |                                                     |
|             |                | -   Operaciones agrupadas `group_by()`              |
|             |                |                                                     |
|             |                | -   `summarise()`                                   |
+-------------+----------------+-----------------------------------------------------+
| Miércoles   | 10:00 - 14:00  | **Visualización de datos con ggplot**               |
|             |                |                                                     |
|             |                | -   Gramática de las gráficas                       |
|             |                |                                                     |
|             |                | -   Geoms y aestethics                              |
+-------------+----------------+-----------------------------------------------------+
| Jueves      | 10::00 - 14:00 | **Visualización de datos con ggplot**               |
|             |                |                                                     |
|             |                | -   Edición                                         |
|             |                |                                                     |
|             |                | -   ggplot sin código                               |
+-------------+----------------+-----------------------------------------------------+
| Viernes     | 10:00 - 14:00  | **Manipulación de datos**                           |
|             |                |                                                     |
|             |                | -   Operaciones por columnas (`across()`)           |
|             |                |                                                     |
|             |                | **Reportes**                                        |
+-------------+----------------+-----------------------------------------------------+

```{r}
#| eval: false
#| include: false


countdown::countdown(1, warn_when = 10)
```
